version: "3.8"

services:
  charm-shop:
    build: .
    ports:
      - 8081:8080
    environment:
      - PG_DB_URL=jdbc:postgresql://postgres:5432/postgres
      - PG_DB_USERNAME=postgres
      - PG_DB_PASSWORD=pass
    container_name: charm_shop_container
    depends_on:
      - postgres
    volumes:
      - ./logs/application.log:/logs/application.log
      
    postgres:
      image: postgres
      ports:
        - 5432:5432
      environment:
        - POSTGRES_PASSWORD=pass
      container_name: postgres_container
      volumes:
       - db-data:/var/lib/postgresql/data
       
volumes:
  db-date:
    driver: local