spring:
  datasource:
    url: ${DB_PG_URL}
    username: ${DB_PG_USERNAME}
    password: ${DB_PG_PASSWORD}
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create 