server:
  http_listen_port: 9080
  grpc_listen_port: 0
  
position:
  filename: /tmp/positions.yaml
  
clients:
  - url: http://loki:3100/loki/api/v1/push
    external_labels:
      host: docker
  
scrape_configs:

  - job_name: docker
    pipeline_stages:
      - docker: {}
    static_configs:
      - labels:
        job: docker
        __path__: /var/lib/docker/containers/*/*-json.log